name: Build Yabause Vita

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITASDK: /usr/local/vitasdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LLVM 21
        run: curl https://apt.llvm.org/llvm.sh | sudo bash -s -- 21

      - name: Checkout vdpm
        uses: actions/checkout@v4
        with:
          repository: vitasdk/vdpm
          path: vdpm

      - name: Install VitaSDK
        run: |
          export VITASDK=/usr/local/vitasdk
          export PATH="$VITASDK/bin:$PATH"
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh

      - name: Configure and Build
        run: |
          export VITASDK=/usr/local/vitasdk
          export PATH="$VITASDK/bin:$PATH"
          # Limpiar el directorio build para evitar caché de CMake
          rm -rf build
          mkdir build
          cd build
          # Forzamos las rutas absolutas para evitar que CMake use el compilador del PC
          cmake -DVITASDK="/usr/local/vitasdk" \
                -DCMAKE_TOOLCHAIN_FILE="/usr/local/vitasdk/share/vita.cmake" \
                -DCMAKE_C_COMPILER="/usr/local/vitasdk/bin/arm-vita-eabi-gcc" \
                -DCMAKE_CXX_COMPILER="/usr/local/vitasdk/bin/arm-vita-eabi-g++" \
                -DYAB_PORTS=vita \
                -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)

      - name: Add BIOS and ROMs folders to VPK
        run: |
          cd build
          # Crear las carpetas y un archivo temporal para que no estén vacías al comprimirlas
          mkdir -p roms bios
          touch roms/.keep bios/.keep
          # Un archivo VPK es básicamente un ZIP. Agregamos las carpetas al VPK generado.
          zip -r YabauseVita.vpk roms/ bios/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yabause-vita
          path: build/YabauseVita.vpk
          if-no-files-found: error
